db:
  url: jdbc:postgresql://127.0.0.1:5432/customers
  user: postgres
  password: root
  driver: org.postgresql.Driver
  pool-size: 20
# choose json parser. Values: jackson, custom
json-parser: jackson
pagination:
  defaultSize: 10