db:
  url: jdbc:postgresql://127.0.0.1:5432/customers
  user: postgres
  password: root
  driver: org.postgresql.Driver
  pool-size: 20

pagination:
  defaultSize: 20

cache:
  type: LRU
  size: 10
  expirationTime: 600

pdf:
  templatePath: src/main/resources/pdf/template/Clevertec_Template.pdf
  destinationDir: results
  fontPath: src/main/resources/pdf/fonts/TimesNewRomanRegular.ttf
  fontSize: 15

liquibase:
  init-db: true
  changeLogFile: db.changelog/changelog-master.yaml